server:
  port: 1080

spring:
  jpa:
    show-sql: false
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate: 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
      cache: 
        use_second_level_cache: false
        use_query_cache: false
        region:
          factory_class: org.hibernate.cache.impl.NoCachingRegionFactory
  thymeleaf:
    cache: false
  datasource:
    name: postgresql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    initialSize: 1
    minIdle: 1
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false    